
srun python -u GAN_exp.py Adiac UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ArrowHead UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Beef UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py BeetleFly UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py BirdChicken UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Car UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py CBF UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ChlorineConcentration UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py CinCECGTorso UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Coffee UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Computers UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py CricketX UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py CricketY UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py CricketZ UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DiatomSizeReduction UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DistalPhalanxOutlineAgeGroup UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DistalPhalanxOutlineCorrect UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DistalPhalanxTW UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Earthquakes UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ECG200 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ECG5000 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ECGFiveDays UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ElectricDevices UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FaceAll UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FaceFour UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FacesUCR UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FiftyWords UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Fish UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FordA UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FordB UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GunPoint UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Ham UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py HandOutlines UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Haptics UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Herring UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py InlineSkate UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py InsectWingbeatSound UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ItalyPowerDemand UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py LargeKitchenAppliances UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Lightning2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Lightning7 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Mallat UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Meat UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MedicalImages UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MiddlePhalanxOutlineCorrect UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MiddlePhalanxOutlineAgeGroup UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MiddlePhalanxTW UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MoteStrain UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py NonInvasiveFetalECGThorax1 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py NonInvasiveFetalECGThorax2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py OliveOil UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py OSULeaf UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PhalangesOutlinesCorrect UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Phoneme UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Plane UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ProximalPhalanxOutlineCorrect UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ProximalPhalanxOutlineAgeGroup UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ProximalPhalanxTW UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py RefrigerationDevices UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ScreenType UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ShapeletSim UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ShapesAll UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SmallKitchenAppliances UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SonyAIBORobotSurface1 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SonyAIBORobotSurface2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py StarLightCurves UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Strawberry UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SwedishLeaf UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Symbols UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SyntheticControl UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ToeSegmentation1 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ToeSegmentation2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Trace UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py TwoLeadECG UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py TwoPatterns UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py UWaveGestureLibraryX UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py UWaveGestureLibraryY UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py UWaveGestureLibraryZ UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py UWaveGestureLibraryAll UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Wafer UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Wine UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py WordSynonyms UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Worms UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py WormsTwoClass UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Yoga UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ACSF1 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py AllGestureWiimoteX UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py AllGestureWiimoteY UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py AllGestureWiimoteZ UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py BME UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Chinatown UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Crop UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py EOGHorizontalSignal UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py EOGVerticalSignal UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py EthanolLevel UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FreezerRegularTrain UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FreezerSmallTrain UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Fungi UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GestureMidAirD1 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GestureMidAirD2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GestureMidAirD3 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GesturePebbleZ1 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GesturePebbleZ2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GunPointAgeSpan UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GunPointMaleVersusFemale UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py GunPointOldVersusYoung UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py HouseTwenty UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py InsectEPGRegularTrain UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py InsectEPGSmallTrain UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MixedShapesRegularTrain UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MixedShapesSmallTrain UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MelbournePedestrian UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PickupGestureWiimoteZ UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PigAirwayPressure UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PigArtPressure UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PigCVP UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PLAID UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PowerCons UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Rock UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SemgHandGenderCh2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SemgHandMovementCh2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SemgHandSubjectCh2 UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ShakeGestureWiimoteZ UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SmoothSubspace UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py UMD UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DodgerLoopDay UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DodgerLoopGame UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DodgerLoopWeekend UCR --loader UCR --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
