
srun python -u GAN_exp.py ArticularyWordRecognition UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8   
srun python -u GAN_exp.py AtrialFibrillation UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py BasicMotions UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py CharacterTrajectories  UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Cricket UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py DuckDuckGeese UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py EigenWorms UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Epilepsy UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py ERing UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py EthanolConcentration UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FaceDetection UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py FingerMovements UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py HandMovementDirection UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Handwriting UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Heartbeat UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py JapaneseVowels UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py Libras UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py LSST UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py MotorImagery UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py NATOPS UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PEMS-SF UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PenDigits UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py PhonemeSpectra UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py RacketSports UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SelfRegulationSCP1 UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SelfRegulationSCP2 UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py SpokenArabicDigits UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py StandWalkJump UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py UWaveGestureLibrary UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
srun python -u GAN_exp.py InsectWingbeat UEA --loader UEA --gpu 0 --epochs 50 --batch_size 16 --lr 0.001 --seed 42 --max-threads 8  
